### PR TITLE
Update WebSecurityConfig.java

### PR DESCRIPTION
**Pull request by somaiah**
configureGlobal is not Autowired. The call should be to an overridden configure(AuthenticationManagerBuilder)

### CODE REVIEW

**Comment by dsyer** [comment]
I think that's incorrect. It *is* marked for autowire and it is called "configureGlobal" because it does something different than the `@Overriden` "configure" method (it's for configuring the"global" parent authentication manager).

**Comment by gregturn** [comment]
This PR is almost two years old. Given the major upgrade to Spring Boot 2.0.0.RELEASE, I believe it's changes are moot.

**Comment by pivotal-issuemaster** [comment]
@somaiah Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-securing-web&pullRequestId=26)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-securing-web&pullRequestId=26) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@somaiah Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-securing-web&pullRequestId=26)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-securing-web&pullRequestId=26) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Pull request closed without merging**
